[package]
name = "binarySearch"
version = "0.1.0"
authors = ["afonso <aj.almeida@campusfct.unl.pt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
